### ISSUE TITLE
Location of binary source

### ISSUE THREAD

**Issue by nevercast** [UDOOboard/mkudoobuntu#1]
Hello UDOOboard!

Just enquiring about the source location of the binaries packaged here, as well as any driver modules that might be needed for hacking on the UDOO board, I'm personally interested in the UDOO Quad as that is the device I own.

https://github.com/UDOOboard/mkudoobuntu/blob/master/binary/uboot-quad.imx

Kind regards, Josh.

**Comment by ektor5** [comment]
Hi Josh!
I forgot to add them in the README, but you can find the sources at
https://github.com/UDOOboard/uboot-imx

BR,
Ek5

2015-10-08 23:04 GMT+02:00 Josh Lloyd notifications@github.com:

> Hello UDOOboard!
> 
> Just enquiring about the source location of the binaries packaged here, as
> well as any driver modules that might be needed for hacking on the UDOO
> board, I'm personally interested in the UDOO Quad as that is the device I
> own.
> 
> https://github.com/UDOOboard/mkudoobuntu/blob/master/binary/uboot-quad.imx
> 
> Kind regards, Josh.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UDOOboard/mkudoobuntu/issues/1.

## 

Ettore Chimenti

Cell: 333-1754004
Skype: ektor-5
