### ISSUE TITLE
mkudoobuntu issue

### ISSUE THREAD

**Issue by oneway3124** [UDOOboard/mkudoobuntu#12]
![image](https://cloud.githubusercontent.com/assets/3787176/14625719/1fd77024-0618-11e6-9595-f5a726fee64f.
![image](https://cloud.githubusercontent.com/assets/3787176/14625724/2b2dae48-0618-11e6-8333-79152f4d9867.png)

**Comment by fmntf** [comment]
Please, add some more info. What did you do? In which host environment?
