### ISSUE TITLE
Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by RoelofBerg** [UDOOboard/mkudoobuntu#14]
Ubuntu 16.04 LTS isn't listed yet in Readme.md.

FYI: 'sudo ./mkudoobuntu.sh udoo-neo minimal' **succeeds** on Ubuntu 16.04 LTS

Is there more that I can test as a contribution to the project ?

**Comment by UDOOboard** [comment]
Readme modified, thanks.
